### PR TITLE
Fix a compile error on linux

### PR DESCRIPTION
**Pull request by alisealy**
Declaring variables immediately after a "case" label causes a compile error using GCC. Adding an empty statement (i.e. a semicolon by itself) before the variable declaration fixes the issue.

### CODE REVIEW

**Comment by sobotka** [comment]
This is a mirror. You need to use the official git.blendee.org site for PRs.

**Comment by alisealy** [comment]
This fix is specific to the spectral-cycles branch

**Comment by sobotka** [comment]
Darn! Sorry! I get these from time to time and generally skip them.

Thanks so much for this. @pembem22 or @Smilebags, would you review please?

**Comment by pembem22** [comment]
Thanks for the PR. Does it compile if you put the code in brackets instead? I think that would be cleaner solution.

**Comment by alisealy** [comment]
> Thanks for the PR. Does it compile if you put the code in brackets instead? I think that would be cleaner solution.

I changed it to use brackets, it compiles fine for me

**Comment by Smilebags** [comment]
Thanks for the PR @alisealy.

If this conforms to the style guide of Blender then I'm happy to merge it. What looks odd is the indentation of the lines, but I'll leave that call to @pembem22.

**Pull request merged**
